# Configuration for Spectrum-Conditioned GeoDiff on QM9

model:
  # --- Original GeoDiff Parameters ---
  type: diffusion
  network: dualenc
  hidden_dim: 128
  num_convs: 6
  num_convs_local: 4
  cutoff: 10.0
  mlp_act: relu
  beta_schedule: quad
  beta_start: 1.e-7
  beta_end: 2.e-3
  num_diffusion_timesteps: 5000
  edge_order: 3
  edge_encoder: mlp
  smooth_conv: false
  spec_cnn_out_dim: 64
  spec_transformer_embed_dim: 64
  spec_num_heads: 4
  spec_num_layers: 3

train:
  seed: 2021
  batch_size: 128 # Reduced batch size due to larger model size
  val_freq: 3000
  max_iters: 1000000000
  max_grad_norm: 10000.0
  anneal_power: 2.0
  optimizer:
    type: adam
    lr: 1.e-3 # Slightly lower learning rate might be needed
    weight_decay: 0.
    beta1: 0.95
    beta2: 0.999
  scheduler:
    scheduler:
    type: cosine           
    T_max: 100000        
    eta_min: 1.0e-6  
#    type: plateau
#    factor: 0.6
#    patience: 5

dataset:
  # --- Updated paths for our new processed dataset ---
  train: ./qme14s_all/train_data.pkl
  val: ./qme14s_all/test_data.pkl
  test: ./qme14s_all/test_data.pkl