# Spectroformer-IB (dualenc_v4) 模型的单阶段训练配置文件

model:
  # --- 核心模型选择 ---
  network: dualenc_v4

  # --- 几何骨干网络参数 (与 dualenc_v3 保持一致) ---
  hidden_dim: 128
  num_convs: 6
  num_convs_local: 4
  cutoff: 10.0
  mlp_act: relu
  edge_order: 3
  edge_encoder: mlp
  smooth_conv: false
  
  # --- 扩散过程参数 ---
  beta_schedule: quad
  beta_start: 1.e-7
  beta_end: 2.e-3
  num_diffusion_timesteps: 5000

  # --- Spectroformer (光谱编码器) 参数 ---
  total_spec_len: 1200          # 光谱总长度 (例如 IR 600 + Raman 600)
  spec_patch_size: 20           # 每个光谱 patch 的大小
  spec_embed_dim: 128           # 光谱 patch 和概念的嵌入维度
  spec_num_heads: 4             # 注意力头的数量
  spec_num_layers: 2            # Spectroformer 内部 Transformer 的层数
  spec_num_concepts: 8          # CIB 压缩后的“光谱概念”数量

train:
  seed: 2021
  batch_size: 32                # 根据显存调整
  val_freq: 3000
  max_iters: 1000000
  max_grad_norm: 1000.0
  anneal_power: 2.0
  
  # CIB 的 KL 散度损失权重
  kl_weight: 1.0e-4

  optimizer:
    type: adam
    lr: 1.e-4
    weight_decay: 0.
    beta1: 0.95
    beta2: 0.999
  
  scheduler:
    type: cosine           
    T_max: 500000        
    eta_min: 1.0e-6  

dataset:
  train: ./qme14s_all/train_data.pkl
  val: ./qme14s_all/test_data.pkl # 建议创建一个独立的验证集
  test: ./qme14s_all/test_data.pkl